language: c
os: linux
compiler:
 - gcc
 - clang
before_install:
 - wget http://lv2plug.in/spec/lv2-1.12.0.tar.bz2
 - wget http://download.drobilla.net/serd-0.22.0.tar.bz2
 - wget http://download.drobilla.net/sord-0.14.0.tar.bz2
 - wget http://download.drobilla.net/sratom-0.4.6.tar.bz2
 - wget http://download.drobilla.net/lilv-0.22.0.tar.bz2
 - wget http://kokkinizita.linuxaudio.org/linuxaudio/downloads/zita-alsa-pcmi-0.2.0.tar.bz2
 - tar xjf lv2-1.12.0.tar.bz2 
 - tar xjf serd-0.22.0.tar.bz2
 - tar xjf sord-0.14.0.tar.bz2
 - tar xjf sratom-0.4.6.tar.bz2
 - tar xjf lilv-0.22.0.tar.bz2
 - tar xjf zita-alsa-pcmi-0.2.0.tar.bz2

 - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
 - sudo add-apt-repository -y ppa:andykimpe/cmake
 - sudo add-apt-repository -y ppa:enlightenment-git/ppa
 - sudo apt-get -q update
install:
 - if [ "$CC" = "clang" ]; then sudo apt-get install -y libstdc++-4.8-dev; fi
 - if [ "$CC" = "gcc" ]; then sudo apt-get install -y gcc-4.8 g++-4.8; fi
 - sudo apt-get install -y libjack-dev libasound2-dev libelementary-dev cmake=2.8.12.2-3
 - pushd lv2-1.12.0 && ./waf configure --prefix=/usr && ./waf build && sudo ./waf install && popd
 - pushd serd-0.22.0 && ./waf configure --prefix=/usr && ./waf build && sudo ./waf install && popd
 - pushd sord-0.14.0 && ./waf configure --prefix=/usr && ./waf build && sudo ./waf install && popd
 - pushd sratom-0.4.6 && ./waf configure --prefix=/usr && ./waf build && sudo ./waf install && popd
 - pushd lilv-0.22.0 && ./waf configure --prefix=/usr && ./waf build && sudo ./waf install && popd
 - pushd zita-alsa-pcmi-0.2.0 && sudo make -C libs PREFIX=/usr LIBDIR=lib install && popd
before_script:
 - if [ "$CC" = "gcc" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
 - mkdir build && pushd build
 - cmake -DBUILD_JACK=1 -DBUILD_ALSA=1 -DCMAKE_BUILD_TYPE=Release ..
 - popd
script:
 - pushd build && make && sudo make install && popd
