language: c
os: linux
compiler:
 - gcc
 - clang
before_install:
 - if [ "$CC" = "clang" ]; then sudo add-apt-repository -y ppa:h-rayflood/llvm-upper; fi
 - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
 - sudo apt-get -q update
install:
 - if [ "$CC" = "clang" ]; then sudo apt-get install -y clang-3.6 libstdc++-5-dev; fi
 - if [ "$CC" = "gcc" ]; then sudo apt-get install -y gcc-5 g++-5; fi
before_script:
 - if [ "$CC" = "clang" ]; then export CXX="clang++-3.6" CC="clang-3.6" CFLAGS="-ffreestanding"; fi
 - if [ "$CC" = "gcc" ]; then export CXX="g++-5" CC="gcc-5"; fi
 - mkdir build && pushd build && cmake -DBUILD_TESTING=1 -DCMAKE_BUILD_TYPE=Debug .. && popd
script:
 - pushd build && make && ARGS="-VV" make test && popd
